#!/bin/bash
# pathways_production_pull keeps pathways_production free for local use while we wait for the heroku db pull to complete
dropdb pathways_production_pull
heroku pg:pull HEROKU_POSTGRESQL_GOLD_URL pathways_production_pull --app pathwaysbc

# # Usage notes:
# For updating local database, the manual script order is:
# > 1. script/pull_prod_db      [attempts to pull latest heroku db backup to pathways_production_pull]
#   2. script/replace_prod_db   [replaces pathways_production with pathways_production_pull (don't run unless step 1 worked)]
#   3. script/import_prod_db    [resets pathways_development back to pathways_production]