#!/bin/bash

heroku pg:reset DATABASE --app pathwaysbcdev --confirm pathwaysbcdev
heroku pg:push pathways_development DATABASE_URL --app pathwaysbcdev
heroku run rake reset_pkey_sequence --app pathwaysbcdev
